version: 2.1
jobs:
  echo:
    docker:
      - image: circleci/python:3.6-browsers
    steps:
      - run: echo "echo echo"
  pila:
    docker:
      - image: circleci/python:3.6-browsers
    # parallelism: 2
    parameters:
      extra-opts:
        type: string
        default: ""
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Reserve pilates
          command: |
            . venv/bin/activate
            python pila.py -u "${USER}" -p "${PASSWORD}" -t "${TIME}" -w 3 \
              -s "${SLACK_TOKEN}" -c "${SLACK_CHANNEL}" << parameters.extra-opts >>

workflows:
  commit:
    jobs:
      - echo
#       - pila:
#           context: soyeon
#       - pila:
#           context: jiye
#       - pila:
#           context: seulb
#       - pila:
#           context: yjung
  openning-soyeon:
    triggers:
      - schedule:
          cron: "50 2 * * 0,2,4"
          filters:
            branches:
              only:
                - master
    jobs:
      - echo
#       - pila:
#           context: soyeon
#           extra-opts : "--wait-opening"
#       - pila:
#           context: jiye
#           extra-opts : "--wait-opening"
#       - pila:
#           context: seulb
#           extra-opts : "--wait-opening"
#       - pila:
#           context: yjung
#           extra-opts : "--wait-opening"
