version: 2.1
jobs:
  echo:
    docker:
      - image: circleci/python:3.6-browsers
    steps:
      - run: echo "echo echo"
  pila:
    docker:
      - image: circleci/python:3.6-browsers
    # parallelism: 2
    parameters:
      extra-opts:
        type: string
        default: ""
      time:
        type: string
        default: ""
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Reserve pilates
          command: |
            . venv/bin/activate
            python pila.py -u "${USER}" -p "${PASSWORD}" -t "<< parameters.time >>" -w 3 \
              -s "${SLACK_TOKEN}" -c "${SLACK_CHANNEL}" << parameters.extra-opts >>

workflows:
  commit:
    jobs:
      - hold:
          type: approval 
      - pila:
          context: soyeon
          time: "월19:00,수19:00,금19:00"
          requires: 
           - hold
      # - pila:
      #     context: jiye
      #     time: "화19:30,수20:00,금20:00"
#       - pila:
#           context: seulb
#           time: "화19:30,수20:00,목19:30,금20:00"
#           requires: 
           - hold
#       - pila:
#           context: somi
#           time: "화19:30,목19:30"
      # - pila:
      #     context: yjung
      #     time: "화19:30,수20:00,금20:00"
  openning-soyeon:
    triggers:
      - schedule:
          cron: "50 2 * * 0,3"
          filters:
            branches:
              only:
                - master
    jobs:
      - pila:
          context: soyeon
          extra-opts: "--wait-opening"
          time: "월19:00,수19:00,금19:00"
      # - pila:
      #     context: jiye
      #     extra-opts: "--wait-opening"
      #     time: "화19:30,수20:00,금20:00"

#       - pila:
#           context: seulb
#           extra-opts: "--wait-opening"
#           time: "화19:30,수20:00,목19:30,금20:00"
#       - pila:
#           context: somi
#           extra-opts: "--wait-opening"
#           time: "화19:30,목19:30"
      # - pila:
      #     context: yjung
      #     extra-opts: "--wait-opening"
      #     time: "화19:30,수20:00,금20:00"
